# Generated by Django 3.1.5 on 2021-01-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intrests',
            field=models.CharField(default='', max_length=255, verbose_name='What is your Intrested Area ?'),
        ),
    ]
