# Generated by Django 3.1.5 on 2021-01-23 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210121_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intrests',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='What is your Intrested Area ?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
