# Generated by Django 3.1.5 on 2021-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210123_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intrests',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
