# Generated by Django 3.1.5 on 2021-01-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210123_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intrests',
        ),
    ]
