# Generated by Django 3.1.5 on 2021-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_profile_intrests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intrestarea',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Intrest Area'),
        ),
    ]
