# Generated by Django 3.1.5 on 2021-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_intrestarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intrestarea',
        ),
        migrations.AddField(
            model_name='profile',
            name='intrests',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
