# Generated by Django 3.1.5 on 2021-02-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_education_educationcategory_educationsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.educationcategory'),
        ),
        migrations.AddField(
            model_name='education',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.educationsubcategory'),
        ),
        migrations.AddField(
            model_name='educationsubcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.educationcategory'),
        ),
    ]
