# Generated by Django 3.1.5 on 2021-02-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210219_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_block',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter Taluka'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city', verbose_name='Enter District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_village',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter Village'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter Degree'),
        ),
    ]
