# Generated by Django 3.1.5 on 2021-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210222_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Profession', 'Profession'), ('Business', 'Business'), ('Government Servant', 'Government Servant'), ('Social Worker', 'Social Worker'), ('Private Job', 'Private Job')], default='', max_length=150, null=True),
        ),
    ]
