# Generated by Django 3.1.5 on 2021-03-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_edusubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.edusubjects'),
        ),
    ]
