# Generated by Django 3.1.5 on 2021-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_education_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edusubjects',
            old_name='sub_name',
            new_name='subject_name',
        ),
    ]
