# Generated by Django 3.1.5 on 2021-03-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210309_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
