# Generated by Django 3.1.5 on 2021-03-11 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_news_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
