# Generated by Django 3.1.5 on 2021-03-12 07:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(blank=True, default='', null=True),
        ),
    ]
