# Generated by Django 3.1.5 on 2021-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210322_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationcategory',
            old_name='image',
            new_name='photo',
        ),
    ]
