# Generated by Django 3.1.5 on 2021-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210322_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='document_path',
            field=models.FileField(blank=True, default='', null=True, upload_to='material/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='educattion/'),
        ),
        migrations.AlterField(
            model_name='educationsubcategory',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='educattion/'),
        ),
        migrations.AlterField(
            model_name='edusubjects',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='educattion/'),
        ),
    ]
