# Generated by Django 3.1.5 on 2021-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210421_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_block',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_city',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter Taluka'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_state',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter State'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Enter Country'),
        ),
    ]
