# Generated by Django 3.1.5 on 2021-04-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0019_auto_20210421_1442'),
        ('home', '0037_auto_20210421_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.teacher'),
        ),
        migrations.AddField(
            model_name='education',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
