# Generated by Django 3.1.5 on 2021-01-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivecyAndProlicy',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
    ]
