# Generated by Django 3.1.5 on 2021-01-22 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_privecyandprolicy_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
