# Generated by Django 3.1.5 on 2021-01-27 04:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20210122_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=255)),
                ('description1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('title2', models.CharField(default='', max_length=255)),
                ('description2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
