# Generated by Django 3.1.5 on 2021-01-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_aboutuscms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuscms',
            old_name='description2',
            new_name='mission_description',
        ),
        migrations.RenameField(
            model_name='aboutuscms',
            old_name='title2',
            new_name='mission_title',
        ),
    ]
