# Generated by Django 3.1.5 on 2021-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_auto_20210127_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/'),
        ),
    ]
