# Generated by Django 3.1.5 on 2021-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_headercms'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercms',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
