# Generated by Django 3.1.5 on 2021-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_footercms'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercms',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
