# Generated by Django 3.1.5 on 2021-01-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin/'),
        ),
    ]
