# Generated by Django 3.1.5 on 2021-04-21 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Full Name')),
                ('skill', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Specialization')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Full Address')),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Email')),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
