# Generated by Django 3.1.5 on 2021-04-21 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
