# Generated by Django 3.1.5 on 2021-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_ebook_ebookcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
