# Generated by Django 3.1.5 on 2021-04-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0024_footercms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
